### ISSUE TITLE
Loopback.io

### ISSUE THREAD

**Issue by 7imbrook** [rit-sse/occurrences#2]

**Comment by weswigham** [comment]
:-1: Pre-configured MEAN stacks are nice when you're starting from scratch, not really so when you're using pre-existing frontends/backends and only replacing one of them. You have to shoehorn existing code to function in the new stack - or start from scratch.

**Comment by kristenmills** [comment]
While I agree with you Wesley, this is pretty much starting from scratch so idk if that changes your opinion at all.

**Comment by weswigham** [comment]
Preconfigured stacks also reduce modularity and increase the likelihood of vendor lock-in, if those are real concerns.

**Comment by kristenmills** [comment]
(Sidenote: I'm probably not doing it...preconfigured stacks are not something I enjoy.)
